In [39]:
import pandas as pd
ba = pd.read_csv('customer_shopping_behavior.csv')

In [40]:
ba.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [41]:
ba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [42]:
ba.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [43]:
ba.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [44]:
ba['Review Rating'] = ba.groupby('Category')['Review Rating'].transform(lambda l:l.fillna(l.median()))

In [45]:
ba.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [46]:
print(ba['Review Rating'])

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [47]:
ba.columns = ba.columns.str.lower()
ba.columns = ba.columns.str.replace(' ', '_')

In [48]:
print(ba.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [49]:
ba = ba.rename(columns = {'purchase_amount_(usd)':'purchase_amount'})

In [50]:
# create a column age group and assign it using qcut
labels=['Young Adult', 'Adult', 'Middle-aged', 'Senior']
ba['age_group'] = pd.qcut(ba['age'], q=4, labels=labels)

In [51]:
ba[['age','age_group']]

      age    age_group
0      55  Middle-aged
1      19  Young Adult
2      50  Middle-aged
3      21  Young Adult
4      45  Middle-aged
...   ...          ...
3895   40        Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44        Adult
3899   52  Middle-aged

[3900 rows x 2 columns]

In [52]:
# create column purchase frequency days
frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

ba['frequency_of_purchases'] = ba['frequency_of_purchases'].map(frequency_mapping)

In [53]:
print(ba['frequency_of_purchases'])

0        14
1        14
2         7
3         7
4       365
       ...
3895      7
3896     14
3897     90
3898      7
3899     90
Name: frequency_of_purchases, Length: 3900, dtype: int64

In [54]:
ba = ba.rename(columns={'frequency_of_purchases': 'frequency_of_purchases_days'})

In [55]:
# check for redundant columns
ba[['discount_applied','promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [56]:
(ba['discount_applied']==ba['promo_code_used']).all()

np.True_

In [57]:
ba = ba.drop('promo_code_used', axis=1)

In [58]:
ba.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases_days,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,14,Middle-aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,14,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,7,Middle-aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,7,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,365,Middle-aged

In [59]:
pip install pymssql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymssql in /Users/ajithattikkachalil/Library/Python/3.9/lib/python/site-packages (2.4.0)
Requirement already satisfied: sqlalchemy in /Users/ajithattikkachalil/Library/Python/3.9/lib/python/site-packages (2.0.52)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/ajithattikkachalil/Library/Python/3.9/lib/python/site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [60]:
# Format and URL-encode the connection attributes
from sqlalchemy import create_engine, text

# Dialect changes to mssql+pymssql
# Syntax: mssql+pymssql://username:password@hostname:port/database
connection_url = "mssql+pymssql://SA:Ajith1234@localhost:1433/customer_behavior"

engine = create_engine(connection_url)

with engine.connect() as connection:
    result = connection.execute(text("SELECT @@VERSION;"))
    print("Connected successfully:", result.scalar())
    table_name="customer"
    ba.to_sql(table_name, engine, if_exists="replace", index=False)

    print("Data successfully loaded in table ", table_name, " database customer_behavior")

Connected successfully: Microsoft Azure SQL Edge Developer (RTM) - 15.0.2000.1574 (ARM64)
	Jan 25 2023 10:36:08
	Copyright (C) 2019 Microsoft Corporation
	Linux (Ubuntu 18.04.6 LTS aarch64) <ARM64>
Data successfully loaded in table  customer  database customer_behavior

In [61]:
ba.to_csv("clean_behavioral_customer.csv", index=False)